management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,prometheus
      path-mapping:
        prometheus: /metrics
  metrics:
    web:
      server:
        requests: true
